Mykhailenko zhelizniak
kmaooad/capstone23 pull request #13
Opened 2023-09-08 21:33 UTC by miksasha

CreateJob and DeleteJob

2023-09-09 07:16 UTC, ironpercival requested changes

2023-09-09 07:16 UTC, ironpercival commented on app/src/main/java/edu/kmaooad/capstone23/orgs/controllers/CreateOrgController.java
комітите пусті рядки, уважніше

2023-09-09 07:16 UTC, ironpercival commented on app/src/main/java/edu/kmaooad/capstone23/orgs/dal/Org.java
а це що?

2023-09-09 16:07 UTC, ElizabethChernova approved these changes

2023-09-09 16:07 UTC, ElizabethChernova commented on app/src/main/java/edu/kmaooad/capstone23/jobs/controllers/DeleteJobController.java
> +public class DeleteJobController  extends TypicalController<DeleteJob, JobDeleted> {
Delete unnecessary comments

2023-09-10 15:16 UTC, VasylPupok approved these changes
За винятком дрібних недоліків на кшталт закоментованих рядків усе гаразд

2023-09-10 19:18 UTC, ironpercival approved these changes

2023-09-11 07:29 UTC, merged