Zymovets kirik
kmaooad/capstone23 pull request #26
Opened 2023-09-11 17:00 UTC by Fourier2718281828

2023-09-11 17:19 UTC, ironpercival requested changes
Proj дуже некрасиво, треба перейменувати на Project

2023-09-11 18:37 UTC, Fourier2718281828 commented
> Proj дуже некрасиво, треба перейменувати на Project

Обрали саме таку назву, опираючись на загальні неймінги у початковом проекті. Здавалося, що Proj більше підходить до Org, ніж Project.

2023-09-11 18:57 UTC, Anoromi approved these changes

2023-09-11 18:57 UTC, Anoromi commented on app/src/main/java/edu/kmaooad/capstone23/competences/handlers/UpdateProjHandler.java
> +    ProjsRepository repository; //intentionally left non-private: https://stackoverflow.com/questions/55101095/why-does-quarkus-warn-me-about-injection-in-private-fields
Не думаю це суттєво додавати в коментарі.

2023-09-11 19:21 UTC, IvanBlyzniuk approved these changes

2023-09-12 04:54 UTC, ironpercival approved these changes
Треба скрізь назвати Project, в т.ч. файли

2023-09-12 04:58 UTC, merged