Feature/ban org\dep\member from the whole system - test ban existing organisation
kmaooad/capstone23 pull request #270
Opened 2023-10-09 05:03 UTC by Anna-Kudiakova

Kudiakova + Budenkova + Parnak

2023-10-09 19:54 UTC, ironpercival approved these changes

2023-10-10 19:32 UTC, dmtroo approved these changes

2023-10-12 17:08 UTC, margoshiiik approved these changes

2023-10-21 15:31 UTC, Anoromi requested changes

2023-10-21 15:31 UTC, Anoromi commented on app/src/main/java/edu/kmaooad/capstone23/access_rules/services/BanService.java
> +    public Result<EntityBanned> banEntity(ObjectId entityId, AccessRuleFromEntityType fromEntityType) {
Сервіси не повинні залежати від ObjectId

2023-10-21 15:31 UTC, Anoromi commented on app/src/main/java/edu/kmaooad/capstone23/access_rules/services/BanService.java
> +public class BanService {
У нас BanService не має ніякого сенсу. Не має місця де він використовувався б.

2023-10-21 15:31 UTC, Anoromi approved these changes

2023-10-21 15:31 UTC, merged