Parnak Budenkova Kudiakova
kmaooad/capstone23 pull request #32
Opened 2023-09-12 05:25 UTC by dmtroo

2023-09-12 06:03 UTC, Dayreks commented on app/src/test/java/edu/kmaooad/capstone23/activities/controllers/CreateExtracurricularActivityControllerTest.java
> +    @Test
@QuarcusTest замість просто @Test

2023-09-12 06:03 UTC, IlliaShev requested changes

2023-09-12 06:03 UTC, IlliaShev commented on app/src/test/java/edu/kmaooad/capstone23/activities/controllers/CreateExtracurricularActivityControllerTest.java
> +
Add @QuarkusTest

2023-09-12 06:04 UTC, Dayreks requested changes
Test errors

2023-09-22 08:56 UTC, ironpercival approved these changes

2023-09-24 13:33 UTC, merged