Fix data persistency before test
kmaooad/capstone23 pull request #69
Opened 2023-09-24 05:59 UTC by Anoromi

Some tests were breaking because of data in mongo db being left from previous tests.

2023-09-24 06:14 UTC, VsevladHort approved these changes

2023-09-24 06:21 UTC, ironpercival commented
якщо вже хочете чистити БД, то мабуть краще робити по-іншому, наприклад через монго драйвер напряму: https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/databases-collections/#drop-a-collection

2023-09-24 06:21 UTC, ironpercival requested changes
див. коментар

2023-09-24 10:31 UTC, jazzandrock approved these changes

2023-09-24 15:16 UTC, Programistich approved these changes

2023-09-25 13:33 UTC, Anoromi commented
> див. коментар

Замінив на ін'єкцію MongoClient

2023-09-28 05:38 UTC, closed without merging