Zahorulko synakevich
kmaooad/capstone23 pull request #9
Opened 2023-09-08 14:58 UTC by jazzandrock

#8

2023-09-08 15:19 UTC, VsevladHort submitted a review, later dismissed

2023-09-08 15:54 UTC, Programistich requested changes

2023-09-08 15:54 UTC, Programistich commented on app/src/main/java/edu/kmaooad/capstone23/common/ErrorCode.java
> +    CHILDREN_PRESENT,
Здається, у такому випадку, буде колізія з іншими командами, оскільки ви зачіпляєте core частину

2023-09-08 15:54 UTC, Programistich commented on app/src/main/java/edu/kmaooad/capstone23/competences/dal/SkillsRepository.java
> +        if(skill.parentSkill != null && findByIdOptional(skill.parentSkill).isEmpty())
Думаю у репозиторії потрібно тільки зберігати, а не обробляти помилки. Логіку по пошуку по id можна винести у Handler

2023-09-08 21:00 UTC, jazzandrock commented on app/src/main/java/edu/kmaooad/capstone23/competences/dal/SkillsRepository.java
> +        if(skill.parentSkill != null && findByIdOptional(skill.parentSkill).isEmpty())
Чому так? Чому ми тоді взагалі створюємо ще один клас `SkillsRepository`, якщо можна просто користуватись методами `mongodb`? Навіщо нам створювати функцію `insert`, якщо можна просто в коді викликати `persist`?

Мені клас `SkillsRepository` виглядає як інтерфейс спілкування з базою даних, і якщо ти будеш користуватись тільки цим класом, твоя база даних буде в хорошому стані завжди. Це наче sql constraints, які ми самі написали.

Сорі, якщо що, я ніколи не працював з таким enterprise grade кодом, тому можу не розуміти очевидних речей)

2023-09-09 07:18 UTC, Programistich commented on app/src/main/java/edu/kmaooad/capstone23/competences/dal/SkillsRepository.java
> +        if(skill.parentSkill != null && findByIdOptional(skill.parentSkill).isEmpty())
> Чому ми тоді взагалі створюємо ще один клас SkillsRepository, якщо можна просто користуватись методами mongodb

Бо ми наслідуємося від параметричного класу, який під капотом буде працювати з Skill

> Навіщо нам створювати функцію insert, якщо можна просто в коді викликати persist?

insert дає змогу повернути об'єкт, бо в ньому, наприклад, буде змінений id, оскільки під час вставки в БД, ми не знаємо PR і це зроблено для зручності

> Мені клас SkillsRepository виглядає як інтерфейс спілкування з базою даних, і якщо ти будеш користуватись тільки цим класом, твоя база даних буде в хорошому стані завжди. Це наче sql constraints, які ми самі написали.

так і є майже, але зараз, тут частина логіки, яка не робить одну ф-цію, а і шукає по ID та тільки потім зберігає. До того ж, тут може повернутися Exception, людина, яка не знає що під капотом, не бачить повний 
"інтерфейс" методу, та може не здогадуватися, що може отримати Exxception

2023-09-09 07:20 UTC, ironpercival submitted a review, later dismissed

2023-09-09 07:24 UTC, ironpercival commented on app/src/main/java/edu/kmaooad/capstone23/common/ErrorCode.java
> +    CHILDREN_PRESENT,
@Programistich  Конструктивна критика передбачає пропозиції рішень. Пропонуйте/конкретизуйте свій варіант, якщо ставите Change Requested.

2023-09-09 07:33 UTC, Anoromi commented on app/src/main/java/edu/kmaooad/capstone23/competences/dal/SkillsRepository.java
> +        if(skill.parentSkill != null && findByIdOptional(skill.parentSkill).isEmpty())
З мого боку, SkillRepository виступає у вигляді DAO для колекції. Перекладати відповідальність з DAO на Handler буде дивно, адже тоді останній матиме декілька відповідальностей.

2023-09-09 07:42 UTC, Anoromi commented on app/src/main/java/edu/kmaooad/capstone23/competences/dal/SkillsRepository.java
> +        if(skill.parentSkill != null && findByIdOptional(skill.parentSkill).isEmpty())
Також, якщо заходити далі, то це повинна бути атомарна операція (транзакція). Вставляти подібні речі у хендлер замість того, щоб виділити операцію в окремий компонент створить забагато проблем.

2023-09-10 11:57 UTC, jazzandrock commented on app/src/main/java/edu/kmaooad/capstone23/common/ErrorCode.java
> +    CHILDREN_PRESENT,
@Programistich дякую, я прибрав власні помилки та замінив їх на `ErrorCode.EXCEPTION`

2023-09-11 06:03 UTC, ironpercival approved these changes

2023-09-11 06:43 UTC, VsevladHort approved these changes

2023-09-11 07:49 UTC, Programistich approved these changes

2023-09-11 08:00 UTC, merged